### ISSUE TITLE
Fichier TaquinFMX.zip KO

### ISSUE THREAD

**Issue by DeveloppeurPascal** [Serge-Girard/Taquin#2]
Le fichier FMX ne se dézippe pas. Peux-tu le retransférer si tu l'as quelque part (ou me l'envoyer en direct pour que je l'ajoute via un PULL REQUEST) ?

**Comment by Serge-Girard** [comment]
Effectivement mon zip est naze aussi, je referai

**Comment by DeveloppeurPascal** [comment]
ah, mince, dommage

**Comment by Serge-Girard** [comment]
Pas de stress, j'ai encore les sources, il me faut juste le temps de refaire ça, j'ai même l'impression d'avoir gardé 2 versions  
dont une avec les Images en Style suite à https://www.developpez.net/forums/blogs/138527-sergiomaster/b10132/utilisation-ludique-style-fmx-jeu-taquin/

**Comment by Serge-Girard** [comment]
Le zip est corrigé
